version : '3'
services:
  project:
    build: ./php
    image: project_php:latest
    container_name: cr101
    hostname: "project"
    volumes:
      - ./src:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html

  nginx_project:
    build: ./nginx
    image: nginx_project:latest
    container_name: nginx_cr101
    hostname: "nginx_project"
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - project
